// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy1D9JXfHeV8XI8UH44PW7vKyHSqsPpUg',
    appId: '1:272584460273:web:e8fff5c560918f84c6a650',
    messagingSenderId: '272584460273',
    projectId: 'portal-aluno-fatec',
    authDomain: 'portal-aluno-fatec.firebaseapp.com',
    storageBucket: 'portal-aluno-fatec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqka2KTn0PIPAhPL43RTp1qj2WhdJDZiY',
    appId: '1:272584460273:android:b00dd39aa643544bc6a650',
    messagingSenderId: '272584460273',
    projectId: 'portal-aluno-fatec',
    storageBucket: 'portal-aluno-fatec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6xbEWkd-Ez5DC65SVqmcKVvoDe1x0sfY',
    appId: '1:272584460273:ios:c649f2dd2f0c0301c6a650',
    messagingSenderId: '272584460273',
    projectId: 'portal-aluno-fatec',
    storageBucket: 'portal-aluno-fatec.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6xbEWkd-Ez5DC65SVqmcKVvoDe1x0sfY',
    appId: '1:272584460273:ios:c649f2dd2f0c0301c6a650',
    messagingSenderId: '272584460273',
    projectId: 'portal-aluno-fatec',
    storageBucket: 'portal-aluno-fatec.firebasestorage.app',
    iosBundleId: 'com.example.portal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1D9JXfHeV8XI8UH44PW7vKyHSqsPpUg',
    appId: '1:272584460273:web:0f4b778d7a80ee0bc6a650',
    messagingSenderId: '272584460273',
    projectId: 'portal-aluno-fatec',
    authDomain: 'portal-aluno-fatec.firebaseapp.com',
    storageBucket: 'portal-aluno-fatec.firebasestorage.app',
  );
}
